app = "finflo"
primary_region = "ord"  # Chicago region, adjust as needed

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8000"
  PYTHONUNBUFFERED = "1"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = false  
  auto_start_machines = true  
  min_machines_running = 1    
  max_machines_running = 1    
  processes = ["app"]

[[statics]]
  guest_path = "/app/staticfiles"
  url_prefix = "/static/"

[checks]
  [checks.status]
    port = 8000
    type = "http"
    path = "/"  # Basic health check at root
    interval = "15s"
    timeout = "10s"
    grace_period = "5s"

[machines]
  size = "shared-cpu-1x"  # Smallest, most cost-effective option
  memory = "1gb"  # Minimum memory
