# Generated by Django 4.2.4 on 2023-08-29 16:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("finflo_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="group",
            options={"permissions": [("view_group_details", "Can view group details")]},
        ),
        migrations.AlterField(
            model_name="group",
            name="members",
            field=models.ManyToManyField(
                related_name="custom_groups", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
