# Generated by Django 4.2.4 on 2023-08-31 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("finflo_app", "0003_transaction_is_recurring_transaction_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="default_currency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="finflo_app.currency",
            ),
        ),
    ]
