# Generated by Django 4.2.4 on 2023-08-31 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finflo_app", "0005_alter_group_default_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="currency",
            name="exchange_rate",
            field=models.DecimalField(decimal_places=4, default=4, max_digits=10),
        ),
    ]
