# Generated by Django 4.2.4 on 2023-09-03 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finflo_app", "0006_alter_currency_exchange_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="categories",
            field=models.ManyToManyField(
                blank=True, related_name="groups", to="finflo_app.category"
            ),
        ),
    ]
