# Generated by Django 4.2.4 on 2023-09-04 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finflo_app", "0007_group_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="is_default",
            field=models.BooleanField(default=False),
        ),
    ]
