# Generated by Django 4.2.4 on 2023-09-10 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finflo_app", "0010_transaction_recurrence_pattern"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="recurrence_pattern",
            field=models.CharField(
                choices=[
                    ("once", "One-time"),
                    ("daily", "Daily"),
                    ("weekly", "Weekly"),
                    ("monthly", "Monthly"),
                ],
                default="once",
                max_length=20,
            ),
        ),
    ]
